# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 501)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.central_layout = QtWidgets.QGridLayout(self.centralWidget)
        self.central_layout.setContentsMargins(11, 11, 11, 11)
        self.central_layout.setSpacing(6)
        self.central_layout.setObjectName("central_layout")
        self.tabs = QtWidgets.QTabWidget(self.centralWidget)
        self.tabs.setObjectName("tabs")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.settings_layout = QtWidgets.QGridLayout(self.settings_tab)
        self.settings_layout.setContentsMargins(11, 11, 11, 11)
        self.settings_layout.setSpacing(6)
        self.settings_layout.setObjectName("settings_layout")
        self.listen_ip = QtWidgets.QPlainTextEdit(self.settings_tab)
        self.listen_ip.setMaximumSize(QtCore.QSize(150, 32))
        self.listen_ip.setTabChangesFocus(True)
        self.listen_ip.setPlaceholderText("")
        self.listen_ip.setObjectName("listen_ip")
        self.settings_layout.addWidget(self.listen_ip, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.settings_tab)
        self.label_2.setObjectName("label_2")
        self.settings_layout.addWidget(self.label_2, 2, 0, 1, 1)
        self.listen_port = QtWidgets.QPlainTextEdit(self.settings_tab)
        self.listen_port.setMaximumSize(QtCore.QSize(70, 32))
        self.listen_port.setObjectName("listen_port")
        self.settings_layout.addWidget(self.listen_port, 0, 2, 1, 1)
        self.remote_port = QtWidgets.QPlainTextEdit(self.settings_tab)
        self.remote_port.setMaximumSize(QtCore.QSize(70, 32))
        self.remote_port.setTabChangesFocus(True)
        self.remote_port.setObjectName("remote_port")
        self.settings_layout.addWidget(self.remote_port, 2, 2, 1, 1)
        self.remote_ip = QtWidgets.QPlainTextEdit(self.settings_tab)
        self.remote_ip.setMaximumSize(QtCore.QSize(150, 32))
        self.remote_ip.setTabChangesFocus(True)
        self.remote_ip.setObjectName("remote_ip")
        self.settings_layout.addWidget(self.remote_ip, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.settings_tab)
        self.label.setObjectName("label")
        self.settings_layout.addWidget(self.label, 0, 0, 1, 1)
        self.tabs.addTab(self.settings_tab, "")
        self.client_hexedit_tab = QtWidgets.QWidget()
        self.client_hexedit_tab.setObjectName("client_hexedit_tab")
        self.client_hexedit_layout = QtWidgets.QGridLayout(self.client_hexedit_tab)
        self.client_hexedit_layout.setContentsMargins(11, 11, 11, 11)
        self.client_hexedit_layout.setSpacing(6)
        self.client_hexedit_layout.setObjectName("client_hexedit_layout")
        self.client_intercept_checkbox = QtWidgets.QCheckBox(self.client_hexedit_tab)
        self.client_intercept_checkbox.setObjectName("client_intercept_checkbox")
        self.client_hexedit_layout.addWidget(self.client_intercept_checkbox, 0, 0, 1, 1)
        self.client_send_button = QtWidgets.QPushButton(self.client_hexedit_tab)
        self.client_send_button.setObjectName("client_send_button")
        self.client_hexedit_layout.addWidget(self.client_send_button, 0, 1, 1, 1)
        self.tabs.addTab(self.client_hexedit_tab, "")
        self.remote_hexedit_tab = QtWidgets.QWidget()
        self.remote_hexedit_tab.setObjectName("remote_hexedit_tab")
        self.remote_hexedit_layout = QtWidgets.QGridLayout(self.remote_hexedit_tab)
        self.remote_hexedit_layout.setContentsMargins(11, 11, 11, 11)
        self.remote_hexedit_layout.setSpacing(6)
        self.remote_hexedit_layout.setObjectName("remote_hexedit_layout")
        self.remote_intercept_checkbox = QtWidgets.QCheckBox(self.remote_hexedit_tab)
        self.remote_intercept_checkbox.setObjectName("remote_intercept_checkbox")
        self.remote_hexedit_layout.addWidget(self.remote_intercept_checkbox, 0, 0, 1, 1)
        self.remote_send_button = QtWidgets.QPushButton(self.remote_hexedit_tab)
        self.remote_send_button.setObjectName("remote_send_button")
        self.remote_hexedit_layout.addWidget(self.remote_send_button, 0, 1, 1, 1)
        self.tabs.addTab(self.remote_hexedit_tab, "")
        self.central_layout.addWidget(self.tabs, 1, 0, 2, 1)
        self.go_button = QtWidgets.QPushButton(self.centralWidget)
        self.go_button.setObjectName("go_button")
        self.central_layout.addWidget(self.go_button, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.listen_ip.setPlainText(_translate("MainWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MainWindow", "Remote IP"))
        self.listen_port.setPlainText(_translate("MainWindow", "10000"))
        self.remote_port.setPlainText(_translate("MainWindow", "8000"))
        self.remote_ip.setPlainText(_translate("MainWindow", "127.0.0.1"))
        self.label.setText(_translate("MainWindow", "Listen IP"))
        self.tabs.setTabText(self.tabs.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.client_intercept_checkbox.setText(_translate("MainWindow", "Intercept"))
        self.client_send_button.setText(_translate("MainWindow", "Send Data"))
        self.tabs.setTabText(self.tabs.indexOf(self.client_hexedit_tab), _translate("MainWindow", "Client Data"))
        self.remote_intercept_checkbox.setText(_translate("MainWindow", "Intercept"))
        self.remote_send_button.setText(_translate("MainWindow", "Send Data"))
        self.tabs.setTabText(self.tabs.indexOf(self.remote_hexedit_tab), _translate("MainWindow", "Remote Data"))
        self.go_button.setText(_translate("MainWindow", "go"))


